dbt_modeling:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      projetct: pipeline-441217
      dataset: "{{ env_var('DBT_DBNAME', 'raw') }}"
      threads: 4
      keyfile: C:\Users\108545\Documents\pessoal\data-modeling\auth\keyfile.json